# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 1601
  thumb-image:
    width: 150
    height: 150
  tracker-list:
    - 192.168.58.128:22122
#    - 185.25.103.20:22122
#    - 192.168.174.42:22122
#    - 192.168.174.48:22122


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/collect?serverTimezone=UTC                # 数据库名称
    username: root
    password: ceshiji
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

mybatis:
  config-location: classpath:mybatis/mybatisConfig.xml      # mybatis配置文件所在路径
  type-aliases-package: com.zjg.collect.dao.model           # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

fdfsdfs:
  group: group01

